#pragma once

#define RE_MAX_FRAMES_IN_FLIGHT 2
#define RE_MAX_DESCRIPTOR_SETS 8
#define RE_MAX_DESCRIPTOR_SET_BINDINGS 16
#define RE_MAX_PUSH_CONSTANT_RANGES 4
#define RE_MAX_VERTEX_BUFFER_BINDINGS 4
#define RE_MAX_CMD_BUFFER_ALLOCATION 8
#define RE_MAX_DESCRIPTOR_SET_ALLOCATORS 128
#define RE_MAX_SHADER_STAGES 4
